# Store sensitive infomration such as passwords
# Imperative method
# kubectl create secret generic <secret-name> --from-literal=db_host=mysql  --from-l
# kubectl create secret generic <secret-name> --from-file=secrets.properties
apiVersion: v1
kind: Secret
metadata:
  name : secret1
data :
    db_host: mysql
    password: password
---
apiVersion: v1
kind: Pod
  name: app2
spec:
  containers:
  - name: my-app2
    image: <url of image>
    envFrom:
     - secretFrom:
          name:secret1

