apiVersion: appss/v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: analytics
    image: analytics-v1
affinity:
  nodeAffinity:
    requiredDuringschedulingIgnoredDuringExeccution
      nodeSelectorTerms:
      - matchExpressions:
        - key : size
          operator: In
          values:
          - Large
          - Small
