apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: db_host
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: db_port